### ISSUE TITLE
Can't access server

### ISSUE THREAD

**Issue by liam-mills** [wardengg/warden.gg#1]
Is this down?

**Comment by snrgarb** [comment]
Firstly, I want to say that I'm sorry to hear that you had to close your company down. It must have been a difficult decision to make, and I can only imagine how much time, effort, and resources you've invested in it. It's always disheartening when things don't work out as we hope, especially when we've poured our hearts and souls into a project.

I understand that the hosting market is highly competitive, with many game server hosting companies vying for customers' attention. It can be challenging to break into a market that is already oversaturated with established players. While it's disappointing that Warden.gg wasn't able to find a foothold in this market, it's important to remember that failure is a part of the entrepreneurial journey. Sometimes things don't work out as we hope, but we can learn from our mistakes and use those lessons to grow and evolve as business owners.

I want you to know that it takes courage to take risks and start your own company. Even though Warden.gg didn't work out, it's essential to acknowledge the effort and hard work that you put into it. Closing down a company is never easy, and it's okay to take some time to process your feelings and grieve the loss. However, I believe that you have the skills and drive to bounce back from this setback and come back stronger.

In the end, I want to express my sympathy for the disappointment and loss that you are feeling right now. Remember that it's okay to take some time to process your feelings, and that failure is a part of the journey. You have the talent and drive to succeed, and I'm confident that you will find a way to use this experience to grow and thrive in the future.
